# SPDX-FileCopyrightText: 2022 George Florea Bănuș <georgefb899@gmail.com>
# SPDX-License-Identifier: CC0-1.0
app-id: org.kde.haruna
runtime: org.kde.Platform
runtime-version: '6.10'
sdk: org.kde.Sdk
command: haruna
rename-icon: haruna
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --device=dri
  - --filesystem=home
  - --filesystem=host:ro
  - --own-name=org.mpris.MediaPlayer2.haruna
  - --share=ipc
  - --share=network
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --socket=wayland
  - --system-talk-name=org.freedesktop.UDisks2
  - --talk-name=org.freedesktop.FileManager1
  - --talk-name=org.freedesktop.ScreenSaver
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/pkgconfig
  - /share/man
modules:
  - name: haruna
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: .
      # - type: archive
      #   url: https://download.kde.org/stable/haruna/1.2.1/haruna-1.2.1.tar.xz
      #   sha256: eb01261a3498c6e25c28064e6ccea37aeb38cd8aa5006f02c92760b124c362fb
      #   x-checker-data:
      #     type: anitya
      #     project-id: 267594
      #     url-template: https://download.kde.org/stable/haruna/$version/haruna-$version.tar.xz
    modules:
      - name: mpvqt
        buildsystem: cmake-ninja
        sources:
          - type: archive
            url: https://download.kde.org/stable/mpvqt/mpvqt-1.1.1.tar.xz
            sha256: bdd1ea69338cf3017f628a886218b8c185ca24e8257f03207a3cf1bbb51e3d32
            x-checker-data:
              type: anitya
              project-id: 370634
              url-template: https://download.kde.org/stable/mpvqt/mpvqt-$version.tar.xz
        modules:
          - name: KDSingleApplication
            buildsystem: cmake-ninja
            builddir: true
            config-opts:
              - -DCMAKE_BUILD_TYPE=Release
              - -DKDSingleApplication_QT6=ON
              - -DKDSingleApplication_EXAMPLES=OFF
            sources:
              - type: archive
                url: https://github.com/KDAB/KDSingleApplication/archive/refs/tags/v1.2.0.tar.gz
                sha256: ff4ae6a4620beed1cdb3e6a9b78a17d7d1dae7139c3d4746d4856b7547d42c38
                x-checker-data:
                  type: anitya
                  project-id: 370439
                  stable-only: true
                  url-template: https://github.com/KDAB/KDSingleApplication/archive/refs/tags/v$version.tar.gz

          - name: libmpv
            cleanup:
              - /share/bash-completion
              - /share/zsh
              - /share/doc
              - /share/icons
              - /share/applications
            buildsystem: meson
            config-opts:
              - -Dlibmpv=true
              - -Dlua=enabled
              - -Ddebug=false
              - -Dbuild-date=false
              - -Dalsa=disabled
              - -Dmanpage-build=disabled
            sources:
              - type: archive
                url: https://github.com/mpv-player/mpv/archive/refs/tags/v0.40.0.tar.gz
                sha256: 10a0f4654f62140a6dd4d380dcf0bbdbdcf6e697556863dc499c296182f081a3
                x-checker-data:
                  type: anitya
                  project-id: 5348
                  stable-only: true
                  url-template: https://github.com/mpv-player/mpv/archive/refs/tags/v$version.tar.gz
            modules:
              - name: luajit
                no-autogen: true
                make-args:
                  - BUILDMODE=dynamic
                  - PREFIX=${FLATPAK_DEST}
                make-install-args:
                  - PREFIX=${FLATPAK_DEST}
                sources:
                  - type: git
                    url: https://github.com/openresty/luajit2.git
                    tag: v2.1-20251030
                    commit: 71fae383f6c4637d64b03a6d0ec76ae8c19d6821
                    x-checker-data:
                      type: git
                      tag-pattern: ^v([\d.-]+)$
                      stable-only: false
                cleanup:
                  - /bin

              - name: libplacebo
                buildsystem: meson
                config-opts:
                  - -Dd3d11=disabled
                  - -Ddemos=False
                sources:
                  - type: archive
                    url: https://code.videolan.org/videolan/libplacebo/-/archive/v7.351.0/libplacebo-v7.351.0.tar.gz
                    sha256: 4efe1c8d4da3c61295eb5fdfa50e6037409d8425eb3c15dd86788679c4ce59ee
                    x-checker-data:
                      type: anitya
                      project-id: 20101
                      stable-only: true
                      url-template: https://code.videolan.org/videolan/libplacebo/-/archive/v$version/libplacebo-v$version.tar.gz
                  - type: patch
                    path: libplacebo-vulkan-python-xml.patch
                  - type: archive
                    url: https://github.com/pallets/jinja/archive/refs/tags/3.1.6.tar.gz
                    sha256: 2074b22a72caa65474902234b320d73463d6d4c223ee49f4b433495758356337
                    dest: 3rdparty/jinja
                    x-checker-data:
                      type: anitya
                      project-id: 3894
                      url-template: https://github.com/pallets/jinja/archive/refs/tags/$version.tar.gz
                  - type: archive
                    url: https://github.com/Dav1dde/glad/archive/refs/tags/v2.0.8.tar.gz
                    sha256: 44f06f9195427c7017f5028d0894f57eb216b0a8f7c4eda7ce883732aeb2d0fc
                    dest: 3rdparty/glad
                    x-checker-data:
                      type: anitya
                      project-id: 300234
                      url-template: https://github.com/Dav1dde/glad/archive/refs/tags/v$version.tar.gz

              - name: libXpresent
                buildsystem: autotools
                sources:
                  - type: archive
                    url: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-1.0.1.tar.xz
                    sha256: b964df9e5a066daa5e08d2dc82692c57ca27d00b8cc257e8e960c9f1cf26231b
                    x-checker-data:
                      type: anitya
                      project-id: 17166
                      stable-only: true
                      url-template: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-$version.tar.xz

              - name: libass
                config-opts:
                  - --disable-static
                sources:
                  - type: archive
                    url: https://github.com/libass/libass/releases/download/0.17.4/libass-0.17.4.tar.gz
                    sha256: a886b3b80867f437bc55cff3280a652bfa0d37b43d2aff39ddf3c4f288b8c5a8
                    x-checker-data:
                      type: anitya
                      project-id: 1560
                      stable-only: true
                      url-template: https://github.com/libass/libass/releases/download/$version/libass-$version.tar.gz

              - name: uchardet
                buildsystem: cmake-ninja
                config-opts:
                  - -DCMAKE_BUILD_TYPE=Release
                  - -DBUILD_STATIC=0
                  - -DCMAKE_POLICY_VERSION_MINIMUM=3.5
                cleanup:
                  - /bin
                sources:
                  - type: archive
                    url: https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.8.tar.xz
                    sha256: e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
                    x-checker-data:
                      type: anitya
                      project-id: 9265
                      stable-only: true
                      url-template: https://www.freedesktop.org/software/uchardet/releases/uchardet-$version.tar.xz

      - name: yt-dlp
        no-autogen: true
        no-make-install: true
        make-args:
          - yt-dlp
          - PYTHON=/usr/bin/python3
        post-install:
          - install yt-dlp /app/bin
        sources:
          - type: archive
            url: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2025.11.12.tar.gz
            sha256: 6f5f2d716968d6c84d05d179fc1ce50ccca23706b9dbbc3c57fec97a8b9ea440
            x-checker-data:
              type: anitya
              project-id: 143399
              stable-only: true
              url-template: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/$version.tar.gz
