# SPDX-FileCopyrightText: 2022 George Florea Bănuș <georgefb899@gmail.com>
# SPDX-License-Identifier: CC0-1.0
app-id: org.kde.haruna
runtime: org.kde.Platform
runtime-version: '6.10'
sdk: org.kde.Sdk
command: haruna
rename-icon: haruna
copy-icon: true
tags:
  - nightly
desktop-file-name-suffix: ' (Nightly)'
finish-args:
  - --share=ipc
  - --share=network
  - --socket=fallback-x11
  - --socket=wayland
  - --socket=pulseaudio
  - --device=dri
  - --filesystem=host:ro
  - --filesystem=home
  - --filesystem=xdg-run/pipewire-0:ro
  - --filesystem=xdg-data/Trash
  - --talk-name=org.freedesktop.ScreenSaver
  - --talk-name=org.freedesktop.FileManager1
  - --own-name=org.mpris.MediaPlayer2.haruna
  - --system-talk-name=org.freedesktop.UDisks2
cleanup:
  - '*.a'
  - '*.la'
  - /include
  - /lib/cmake
  - /lib/pkgconfig
  - /share/man
  - /mkspecs
modules:
  - name: haruna
    buildsystem: cmake-ninja
    sources:
      - type: dir
        path: .
      # - type: archive
      #   url: https://download.kde.org/stable/haruna/1.2.1/haruna-1.2.1.tar.xz
      #   sha256: eb01261a3498c6e25c28064e6ccea37aeb38cd8aa5006f02c92760b124c362fb
      #   x-checker-data:
      #     type: anitya
      #     project-id: 267594
      #     url-template: https://download.kde.org/stable/haruna/$version/haruna-$version.tar.xz
    modules:
      - name: KDSingleApplication
        buildsystem: cmake-ninja
        cleanup:
          - /share/doc
        builddir: true
        config-opts:
          - -DCMAKE_BUILD_TYPE=Release
          - -DKDSingleApplication_QT6=ON
          - -DKDSingleApplication_EXAMPLES=OFF
        sources:
          - type: archive
            url: https://github.com/KDAB/KDSingleApplication/archive/refs/tags/v1.2.0.tar.gz
            sha256: ff4ae6a4620beed1cdb3e6a9b78a17d7d1dae7139c3d4746d4856b7547d42c38
            x-checker-data:
              type: anitya
              project-id: 370439
              stable-only: true
              url-template: https://github.com/KDAB/KDSingleApplication/archive/refs/tags/v$version.tar.gz

      - name: mpvqt
        buildsystem: cmake-ninja
        sources:
          - type: archive
            url: https://download.kde.org/stable/mpvqt/mpvqt-1.1.1.tar.xz
            sha256: bdd1ea69338cf3017f628a886218b8c185ca24e8257f03207a3cf1bbb51e3d32
            x-checker-data:
              type: anitya
              project-id: 370634
              url-template: https://download.kde.org/stable/mpvqt/mpvqt-$version.tar.xz
        modules:
          - name: libmpv
            cleanup:
              - /share/bash-completion
              - /share/fish
              - /share/zsh
              - /share/doc
              - /share/icons
              - /share/applications
            buildsystem: meson
            config-opts:
              - -Dlibmpv=true
              - -Dlua=enabled
              - -Ddebug=false
              - -Dbuild-date=false
              - -Dalsa=disabled
              - -Dmanpage-build=disabled
            sources:
              - type: archive
                url: https://github.com/mpv-player/mpv/archive/refs/tags/v0.41.0.tar.gz
                sha256: ee21092a5ee427353392360929dc64645c54479aefdb5babc5cfbb5fad626209
                x-checker-data:
                  type: anitya
                  project-id: 5348
                  stable-only: true
                  url-template: https://github.com/mpv-player/mpv/archive/refs/tags/v$version.tar.gz
            modules:
              - name: luajit
                no-autogen: true
                make-args:
                  - BUILDMODE=dynamic
                  - PREFIX=${FLATPAK_DEST}
                make-install-args:
                  - PREFIX=${FLATPAK_DEST}
                sources:
                  - type: git
                    url: https://github.com/openresty/luajit2.git
                    tag: v2.1-20260311
                    commit: 3640b6c590f9c383ffa5d0955f35e646f684a1da
                    x-checker-data:
                      type: git
                      tag-pattern: ^v([\d.-]+)$
                      stable-only: false
                cleanup:
                  - /bin

              - name: libplacebo
                buildsystem: meson
                config-opts:
                  - -Ddemos=false
                cleanup:
                  - /include
                  - /lib/pkgconfig
                sources:
                  - type: git
                    url: https://github.com/haasn/libplacebo.git
                    tag: v7.360.1
                    commit: cee9b076f2c63104ccfd497fa79c39a867293ec4
                    x-checker-data:
                      type: git
                      tag-pattern: ^v([\d.]+)$

              - name: libXpresent
                buildsystem: autotools
                sources:
                  - type: archive
                    url: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-1.0.2.tar.xz
                    sha256: 4e5b21b4812206a4b223013606ae31170502c1043038777a1ef8f70c09d37602
                    x-checker-data:
                      type: anitya
                      project-id: 17166
                      stable-only: true
                      url-template: https://xorg.freedesktop.org/archive/individual/lib/libXpresent-$version.tar.xz

              - name: libass
                config-opts:
                  - --disable-static
                sources:
                  - type: archive
                    url: https://github.com/libass/libass/releases/download/0.17.4/libass-0.17.4.tar.gz
                    sha256: a886b3b80867f437bc55cff3280a652bfa0d37b43d2aff39ddf3c4f288b8c5a8
                    x-checker-data:
                      type: anitya
                      project-id: 1560
                      stable-only: true
                      url-template: https://github.com/libass/libass/releases/download/$version/libass-$version.tar.gz

              - name: uchardet
                buildsystem: cmake-ninja
                config-opts:
                  - -DCMAKE_BUILD_TYPE=Release
                  - -DBUILD_STATIC=0
                  - -DCMAKE_POLICY_VERSION_MINIMUM=3.5
                cleanup:
                  - /bin
                sources:
                  - type: archive
                    url: https://www.freedesktop.org/software/uchardet/releases/uchardet-0.0.8.tar.xz
                    sha256: e97a60cfc00a1c147a674b097bb1422abd9fa78a2d9ce3f3fdcc2e78a34ac5f0
                    x-checker-data:
                      type: anitya
                      project-id: 9265
                      stable-only: true
                      url-template: https://www.freedesktop.org/software/uchardet/releases/uchardet-$version.tar.xz

      - name: yt-dlp
        no-autogen: true
        no-make-install: true
        make-args:
          - yt-dlp
          - PYTHON=/usr/bin/python3
        post-install:
          - install yt-dlp /app/bin
        sources:
          - type: archive
            url: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2026.03.17.tar.gz
            sha256: 924483986441d8a1e669a0e4371d753a9256ce4bdc06032394ccb7b793342434
            x-checker-data:
              type: anitya
              project-id: 143399
              stable-only: true
              url-template: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/$version.tar.gz
