# SPDX-FileCopyrightText: 2024, 2026 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: haruna
confinement: strict
grade: stable
base: core24
adopt-info: haruna
icon: $CRAFT_PROJECT_DIR/data/icons/128-apps-haruna.png
apps:
  haruna:
    extensions:
      - kde-neon-6
    common-id: org.kde.haruna
    desktop: usr/share/applications/org.kde.haruna.desktop
    command: usr/bin/haruna
    plugs:
      - home
      - audio-record
      - removable-media
    environment:
      PYTHONPYCACHEPREFIX: "$SNAP_USER_COMMON/.pycache"
      PYTHONUSERBASE: $SNAP_USER_COMMON/.local
      PIP_USER: 1
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:${PYTHONPATH}
      GST_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SYSTEM_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer-1.0
      GST_PLUGIN_SCANNER: $SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET/gstreamer1.0/gstreamer-1.0/gst-plugin-scanner
      QT_QUICK_CONTROLS_STYLE: org.kde.breeze
      ALSA_CONFIG_PATH: "$SNAP/kf6/etc/asound.conf"
      LD_LIBRARY_PATH: "$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:${LD_LIBRARY_PATH}"
      PATH: $SNAP/ffmpeg-platform/usr/bin:$SNAP/usr/bin:${PATH}
plugs:
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform # the folder where this content snap will be mounted
    default-provider: ffmpeg-2404
layout:
  "/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib":
    bind: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/alsa-lib"
  "/usr/share/alsa":
    bind: "$SNAP/usr/share/alsa"
  "/etc/alsa/conf.d":
    bind: "$SNAP/etc/alsa/conf.d"
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.haruna
    bus: session
parts:
  python-deps:
    source: .
    plugin: python
    python-packages:
      - yt-dlp
      - youtube-dl
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.12
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.12
      - -usr/bin/wheel
      - -usr/lib/python3.12/dist-packages/pip*
      - -usr/lib/python3.12/dist-packages/pkg_resources
      - -usr/lib/python3.12/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.12/site-packages: usr/lib/python3/dist-packages
  kdsingleapplication:
    plugin: cmake
    source: https://github.com/KDAB/KDSingleApplication.git
    source-branch: master
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
      - -DKDSingleApplication_EXAMPLES=FALSE
  mpvqt:
    plugin: cmake
    source: https://invent.kde.org/libraries/mpvqt.git
    source-branch: master
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
    build-packages:
      - libmpv-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
  haruna:
    after:
      - kdsingleapplication
      - mpvqt
      - python-deps
    parse-info:
      - usr/share/metainfo/org.kde.haruna.metainfo.xml
    plugin: cmake
    build-snaps:
      - kde-qt6-core24-sdk/latest/beta
      - kf6-core24-sdk/latest/beta
      - ffmpeg-2404-sdk
    build-packages:
      - libmpv-dev
    stage-packages:
      - gstreamer1.0-alsa
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-libav
      - libasound2
      - libasound2-data
      - libasound2-plugins
      - libasound2-plugins-extra
      - libmpv2
    source: .
    source-type: local
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_WITH_QT6=ON
      - -DBUILD_TESTING=OFF
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/doc/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0"
      - "-usr/lib/aspell/*"
  gpu-2404:
    after: [haruna]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - haruna
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
      - ffmpeg-2404
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24" "ffmpeg-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
